language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script: vendor/bin/phpunit